# -*- coding: utf-8 -*-
"""pipeline RAG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12FjeFHBOD3bSj_M6xkKImj9saGNe1PQo

# 1. Importation des bibliotheques
"""

!pip install langchain langchain-community langchain-google-genai chromadb pypdf python-dotenv streamlit
!pip install langchain-groq sentence-transformers
!pip install langchain-google-vertexai

!pip install langchain-text-splitters

import os
from langchain_community.document_loaders import PyPDFLoader, TextLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter

"""# 2. Chargement du fichier selon son extension (.pdf, .txt, .docx)"""

from pathlib import Path
import pandas as pd # Assuming pandas is needed for DataFrame, though not explicitly in original error trace but good practice.

document_path = "/content/camus_mort_heureuse.pdf" # Correcting incomplete path

def charger_pdf(chemin):
    from pypdf import PdfReader
    reader = PdfReader(chemin)
    pages = []
    for i, page in enumerate(reader.pages):
        texte = page.extract_text() or ""
        pages.append({"page": i + 1, "text": texte})
    return pages


def charger_txt(chemin):
    with open(chemin, "r", encoding="utf-8") as f:
        return [{"page": 1, "text": f.read()}]


def charger_docx(chemin):
    from docx import Document
    doc = Document(chemin)
    texte = "\n".join(p.text for p in doc.paragraphs)
    return [{"page": 1, "text": texte}]


def charger_document(chemin):
    """Charge un fichier selon son extension et retourne une liste de pages {page, text}."""
    chemin = Path(chemin)
    extension = chemin.suffix.lower()

    if extension == ".pdf":
        pages = charger_pdf(chemin)
    elif extension == ".txt":
        pages = charger_txt(chemin)
    elif extension == ".docx":
        pages = charger_docx(chemin)
    else:
        raise ValueError(f"Extension non supportée : {extension} (attendu : .pdf, .txt, .docx)")

    for p in pages:
        p["document"] = chemin.name
        p["source"] = str(chemin)
    return pages


# --- Chargement des documents de TontoumaBot ---
DATA_DIR = Path("data")
DATA_DIR.mkdir(exist_ok=True)

chemins_documents = sorted(list(DATA_DIR.glob("*.pdf")) + list(DATA_DIR.glob("*.txt")) + list(DATA_DIR.glob("*.docx")))

if not chemins_documents:
    print(f"⚠️  Aucun document trouvé dans {DATA_DIR}/ — dépose orientation_rag.pdf et")
    print("   donnees_fictives_procedures_rag.pdf (ou tes propres fichiers) avant de continuer.")
else:
    print(f"{len(chemins_documents)} document(s) trouvé(s) :")
    for c in chemins_documents:
        print(f"  - {c.name}")

toutes_les_pages = []
for chemin in chemins_documents:
    try:
        pages = charger_document(chemin)
        toutes_les_pages.extend(pages)
        print(f"✅ {chemin.name} : {len(pages)} page(s) extraite(s)")
    except Exception as e:
        print(f"❌ {chemin.name} : {e}")

df_pages = pd.DataFrame(toutes_les_pages)
if not df_pages.empty:
    df_pages["n_caracteres"] = df_pages["text"].str.len()
    print(f"\nTotal : {len(df_pages)} pages, {df_pages['n_caracteres'].sum()} caractères")
    display(df_pages[["document", "page", "n_caracteres"]])

"""
## 3. Configuration du découpeur de texte (Text Splitter)

Découpage intelligent : d'abord par section structurée (`PROC-XXX`, `BAT-X`, titres en `##`), puis par taille uniquement pour le texte qui reste trop long."""

import re

CHUNK_SIZE = 500
CHUNK_OVERLAP = 100

try:
    from langchain_text_splitters import RecursiveCharacterTextSplitter
    splitter = RecursiveCharacterTextSplitter(
        chunk_size=CHUNK_SIZE,
        chunk_overlap=CHUNK_OVERLAP,
        separators=["\n\n", "\n", ". ", " ", ""],
    )
    LANGCHAIN_OK = True
    print(f"Text splitter LangChain configuré : chunk_size={CHUNK_SIZE}, chunk_overlap={CHUNK_OVERLAP}")
except ImportError:
    LANGCHAIN_OK = False
    print("  langchain-text-splitters non installé -> pip install langchain-text-splitters")
    print("   Un découpage par taille manuel sera utilisé en repli (cellule suivante).")


# Motif de détection des sections structurées (procédures, bâtiments, titres)
MOTIF_SECTION = re.compile(r"(PROC-\d{3}[^\n]*|BAT-[A-Z][^\n]*|##\s+[^\n]+)")

print("Configuration du chunking prête.")

"""## 4. Découpage en morceaux (chunks)

Priorité au découpage par section structurée ; le texte hors section passe par le text splitter à taille fixe.
"""

def decouper_par_taille(texte, chunk_size=CHUNK_SIZE, chunk_overlap=CHUNK_OVERLAP):
    if LANGCHAIN_OK:
        return splitter.split_text(texte)
    # Repli manuel si langchain n'est pas installé
    morceaux = []
    debut = 0
    while debut < len(texte):
        fin = debut + chunk_size
        morceaux.append(texte[debut:fin])
        debut += chunk_size - chunk_overlap
    return morceaux


def decouper_intelligemment(texte, document, page):
    """Découpe par section structurée si détectée, sinon par taille fixe."""
    sections = MOTIF_SECTION.split(texte)
    chunks = []

    if len(sections) > 1:
        # sections[0] = texte avant la 1ère section (souvent du bruit d'en-tête)
        # puis alternance [titre_section, contenu, titre_section, contenu, ...]
        i = 1
        while i < len(sections) - 1:
            titre = sections[i].strip()
            contenu = sections[i + 1].strip()
            texte_complet = f"{titre}\n{contenu}"
            if len(texte_complet) > CHUNK_SIZE * 1.5:
                for sous_morceau in decouper_par_taille(texte_complet):
                    chunks.append({"section": titre, "text": sous_morceau})
            else:
                chunks.append({"section": titre, "text": texte_complet})
            i += 2
    else:
        # Pas de section structurée détectée -> découpage par taille uniquement
        for morceau in decouper_par_taille(texte):
            chunks.append({"section": f"{document} p.{page}", "text": morceau})

    return chunks


tous_les_chunks = []
compteur_id = 0
for _, ligne in df_pages.iterrows():
    chunks_page = decouper_intelligemment(ligne["text"], ligne["document"], ligne["page"])
    for c in chunks_page:
        compteur_id += 1
        tous_les_chunks.append({
            "chunk_id": f"CH-{compteur_id:04d}",
            "document": ligne["document"],
            "page": ligne["page"],
            "section": c["section"],
            "text": c["text"],
        })

df_chunks = pd.DataFrame(tous_les_chunks)
df_chunks = df_chunks[df_chunks["text"].str.strip().str.len() > 10].reset_index(drop=True)  # retire les chunks vides/bruit

print(f"{len(df_chunks)} chunks créés à partir de {len(df_pages)} pages.")
display(df_chunks[["chunk_id", "document", "page", "section"]].head(10))

df_chunks.tail(20)

"""## 5. Metadata Enrichment"""

def enrichir_metadata(df):
    df = df.copy()
    df["n_caracteres"] = df["text"].str.len()
    df["n_mots"] = df["text"].str.split().str.len()

    # Type de contenu déduit du motif de section détecté
    df["type_contenu"] = df["section"].apply(
        lambda s: "procedure" if s.startswith("PROC-")
        else "orientation" if s.startswith("BAT-")
        else "section" if s.startswith("##")
        else "generique"
    )

    df["langue_probable"] = "fr"  # les documents fictifs sont en français ; à ajuster si corpus multilingue
    df["date_indexation"] = pd.Timestamp.now().isoformat()

    return df


df_chunks = enrichir_metadata(df_chunks)
print("Métadonnées enrichies : n_caracteres, n_mots, type_contenu, langue_probable, date_indexation")
display(df_chunks[["chunk_id", "type_contenu", "n_caracteres", "n_mots"]].head(10))

print("\nRépartition par type de contenu :")
print(df_chunks["type_contenu"].value_counts().to_string())

"""## 6. Embedding"""

import time

EMBEDDING_MODEL = "BAAI/bge-m3"  # modifiable ; repli automatique si indisponible

from sentence_transformers import SentenceTransformer

try:
    embedder = SentenceTransformer(EMBEDDING_MODEL)
    print(f" Modèle d'embedding chargé : {EMBEDDING_MODEL}")
except Exception as e:
    print(f"⚠️  Échec du chargement de {EMBEDDING_MODEL} ({e}) — repli sur un modèle plus léger.")
    EMBEDDING_MODEL = "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
    embedder = SentenceTransformer(EMBEDDING_MODEL)
    print(f" Modèle de repli chargé : {EMBEDDING_MODEL}")

t0 = time.time()
embeddings_chunks = embedder.encode(df_chunks["text"].tolist(), normalize_embeddings=True, show_progress_bar=True)
print(f"\n{embeddings_chunks.shape[0]} chunks encodés en {time.time()-t0:.1f}s — dimension {embeddings_chunks.shape[1]}")

"""## 7. ChromaDB (vector store)"""

import chromadb

client_chroma = chromadb.Client()  # en mémoire ; utilise chromadb.PersistentClient(path="...") pour persister sur disque

# Repartir d'une collection propre à chaque exécution du notebook
try:
    client_chroma.delete_collection("tontoumabot_chunks")
except Exception:
    pass

collection = client_chroma.create_collection(name="tontoumabot_chunks")

collection.add(
    ids=df_chunks["chunk_id"].tolist(),
    embeddings=embeddings_chunks.tolist(),
    documents=df_chunks["text"].tolist(),
    metadatas=df_chunks[["document", "page", "section", "type_contenu"]].to_dict("records"),
)

print(f"✅ {collection.count()} chunks indexés dans ChromaDB (collection 'tontoumabot_chunks').")

"""## 8. Recherche hybride (BM25 + Vector Search)"""

!pip install rank_bm25

import numpy as np
from rank_bm25 import BM25Okapi

def tokeniser_simple(texte):
    return re.findall(r"\w+", texte.lower())


corpus_tokenise = [tokeniser_simple(t) for t in df_chunks["text"].tolist()]
bm25 = BM25Okapi(corpus_tokenise)

print(f"Index BM25 construit sur {len(corpus_tokenise)} chunks.")


def recherche_vectorielle(question, top_k=10):
    """Recherche dense via ChromaDB. Retourne une liste de (chunk_id, score) triée par pertinence."""
    embedding_question = embedder.encode([question], normalize_embeddings=True)[0]
    resultats = collection.query(query_embeddings=[embedding_question.tolist()], n_results=top_k)
    # ChromaDB retourne une distance (plus bas = plus proche) ; on la convertit en score de similarité
    ids = resultats["ids"][0]
    distances = resultats["distances"][0]
    scores = [1 - d for d in distances]  # approximation cosine similarity à partir de la distance
    return list(zip(ids, scores))


def recherche_bm25(question, top_k=10):
    """Recherche lexicale BM25. Retourne une liste de (chunk_id, score) triée par pertinence."""
    scores = bm25.get_scores(tokeniser_simple(question))
    indices_tries = np.argsort(-scores)[:top_k]
    return [(df_chunks.iloc[i]["chunk_id"], float(scores[i])) for i in indices_tries]


# Test rapide
question_test = "Comment obtenir un extrait de naissance ?"
print("Dense :", recherche_vectorielle(question_test, top_k=3))
print("BM25  :", recherche_bm25(question_test, top_k=3))

"""## 9. Fusion

Fusion des deux classements (dense + BM25) par **Reciprocal Rank Fusion (RRF)** — combine les rangs plutôt que les scores bruts, qui ne sont pas sur la même échelle entre BM25 et cosine similarity.
"""

def fusion_rrf(liste_resultats, k=60):
    """
    Reciprocal Rank Fusion : combine plusieurs classements (chacun une liste de (id, score)
    triée par pertinence décroissante) en un score fusionné unique par id.
    """
    scores_fusionnes = {}
    for resultats in liste_resultats:
        for rang, (chunk_id, _) in enumerate(resultats, start=1):
            scores_fusionnes[chunk_id] = scores_fusionnes.get(chunk_id, 0) + 1 / (k + rang)
    return sorted(scores_fusionnes.items(), key=lambda x: -x[1])


def recherche_hybride(question, top_k=10):
    resultats_dense = recherche_vectorielle(question, top_k=top_k)
    resultats_bm25 = recherche_bm25(question, top_k=top_k)
    fusionnes = fusion_rrf([resultats_dense, resultats_bm25])
    return fusionnes[:top_k]


resultats_fusionnes = recherche_hybride(question_test, top_k=10)
print("Résultats fusionnés (RRF) :")
for chunk_id, score in resultats_fusionnes[:5]:
    texte = df_chunks.loc[df_chunks["chunk_id"] == chunk_id, "text"].values[0]
    print(f"  {chunk_id} (score={score:.4f}) : {texte[:80]}...")

"""## 10. MMR (Maximal Marginal Relevance)

Réduit la redondance entre les chunks sélectionnés : privilégie un chunk pertinent MAIS différent de ceux déjà choisis, plutôt que plusieurs chunks très similaires entre eux.
"""

def mmr(question, candidats_ids, top_k=5, lambda_diversite=0.5):
    """
    candidats_ids : liste de chunk_id déjà présélectionnés (ex. sortie de la fusion)
    lambda_diversite : 1 = uniquement la pertinence, 0 = uniquement la diversité
    """
    if not candidats_ids:
        return []

    embedding_question = embedder.encode([question], normalize_embeddings=True)[0]
    indices_candidats = [df_chunks.index[df_chunks["chunk_id"] == cid][0] for cid in candidats_ids]
    embeddings_candidats = embeddings_chunks[indices_candidats]

    similarites_question = embeddings_candidats @ embedding_question

    selectionnes = []
    restants = list(range(len(candidats_ids)))

    while restants and len(selectionnes) < top_k:
        if not selectionnes:
            meilleur = max(restants, key=lambda i: similarites_question[i])
        else:
            def score_mmr(i):
                sim_max_selectionnes = max(
                    embeddings_candidats[i] @ embeddings_candidats[j] for j in selectionnes
                )
                return lambda_diversite * similarites_question[i] - (1 - lambda_diversite) * sim_max_selectionnes
            meilleur = max(restants, key=score_mmr)

        selectionnes.append(meilleur)
        restants.remove(meilleur)

    return [candidats_ids[i] for i in selectionnes]


ids_fusionnes = [cid for cid, _ in resultats_fusionnes]
ids_apres_mmr = mmr(question_test, ids_fusionnes, top_k=5, lambda_diversite=0.5)
print("Chunks retenus après MMR :", ids_apres_mmr)

"""## 11. Filtering

Filtre les chunks selon un seuil de pertinence minimal (évite de transmettre au LLM un chunk trop faiblement lié à la question) et/ou selon des critères de métadonnées.
"""

SEUIL_SCORE_MIN = 0.01  # seuil sur le score RRF fusionné ; à ajuster selon l'échelle observée


def filtrer_chunks(candidats_ids, scores_fusion, seuil=SEUIL_SCORE_MIN, type_contenu_autorise=None):
    dict_scores = dict(scores_fusion)
    filtres = []
    for cid in candidats_ids:
        if dict_scores.get(cid, 0) < seuil:
            continue
        if type_contenu_autorise is not None:
            type_c = df_chunks.loc[df_chunks["chunk_id"] == cid, "type_contenu"].values[0]
            if type_c not in type_contenu_autorise:
                continue
        filtres.append(cid)
    return filtres


ids_filtres = filtrer_chunks(ids_apres_mmr, resultats_fusionnes, seuil=SEUIL_SCORE_MIN)
print(f"{len(ids_filtres)}/{len(ids_apres_mmr)} chunks conservés après filtrage (seuil={SEUIL_SCORE_MIN}).")
print(ids_filtres)

"""## 12. Reranking

Cross-encoder qui réévalue précisément la pertinence question/chunk (plus lent mais plus fin que la similarité d'embeddings seule).
"""

RERANKER_MODEL = "cross-encoder/ms-marco-MiniLM-L-6-v2"

try:
    from sentence_transformers import CrossEncoder
    reranker = CrossEncoder(RERANKER_MODEL)
    RERANKER_OK = True
    print(f"✅ Reranker chargé : {RERANKER_MODEL}")
except Exception as e:
    RERANKER_OK = False
    print(f"⚠️  Reranker non chargé ({e}) — les chunks filtrés seront utilisés tels quels, sans réordonnancement fin.")


def reranker_chunks(question, candidats_ids, top_k=5):
    if not candidats_ids:
        return []
    if not RERANKER_OK:
        return candidats_ids[:top_k]

    textes = [df_chunks.loc[df_chunks["chunk_id"] == cid, "text"].values[0] for cid in candidats_ids]
    paires = [[question, texte] for texte in textes]
    scores = reranker.predict(paires)

    ordre = np.argsort(-scores)
    return [candidats_ids[i] for i in ordre[:top_k]], [float(scores[i]) for i in ordre[:top_k]]


ids_reranked, scores_reranked = reranker_chunks(question_test, ids_filtres, top_k=5)
print(f"\nTop-{len(ids_reranked)} chunks après reranking :")
for cid, score in zip(ids_reranked, scores_reranked):
    print(f"  {cid} (score={score:.2f})")

"""## 13. Fonction complète de récupération (Top-K chunks)

Assemble toutes les étapes précédentes en une seule fonction réutilisable.
"""

def recuperer_chunks(question, top_k_hybride=10, top_k_mmr=5, top_k_final=5, seuil_filtre=SEUIL_SCORE_MIN):
    t0 = time.perf_counter()
    resultats_fusionnes = recherche_hybride(question, top_k=top_k_hybride)
    t_hybride = time.perf_counter() - t0

    ids_fusionnes = [cid for cid, _ in resultats_fusionnes]

    t0 = time.perf_counter()
    ids_mmr = mmr(question, ids_fusionnes, top_k=top_k_mmr)
    t_mmr = time.perf_counter() - t0

    t0 = time.perf_counter()
    ids_filtres = filtrer_chunks(ids_mmr, resultats_fusionnes, seuil=seuil_filtre)
    t_filtre = time.perf_counter() - t0

    t0 = time.perf_counter()
    if RERANKER_OK:
        ids_finaux, scores_finaux = reranker_chunks(question, ids_filtres, top_k=top_k_final)
    else:
        ids_finaux = ids_filtres[:top_k_final]
        scores_finaux = [None] * len(ids_finaux)
    t_rerank = time.perf_counter() - t0

    chunks_textes = [df_chunks.loc[df_chunks["chunk_id"] == cid, "text"].values[0] for cid in ids_finaux]

    latences = {
        "hybride_ms": round(t_hybride * 1000, 1), "mmr_ms": round(t_mmr * 1000, 1),
        "filtre_ms": round(t_filtre * 1000, 1), "rerank_ms": round(t_rerank * 1000, 1),
    }
    latences["retrieval_total_ms"] = round(sum(latences.values()), 1)

    return {
        "chunk_ids": ids_finaux, "textes": chunks_textes, "scores": scores_finaux, "latences": latences,
    }


resultat_test = recuperer_chunks(question_test)
print("Chunks récupérés :", resultat_test["chunk_ids"])
print("Latences :", resultat_test["latences"])

"""## 14. LLM et génération de la réponse contextualisée

Modèle local léger par défaut (facilement remplaçable par un appel API Groq/Gemini en production, comme dans TontoumaBot V2).
"""

LLM_MODEL = "Qwen/Qwen2.5-1.5B-Instruct"  # remplaçable par un appel API (Groq, Gemini...) en production

from transformers import pipeline

generator = pipeline("text-generation", model=LLM_MODEL)
print(f"✅ LLM chargé : {LLM_MODEL}")

ROLE_SYSTEME = (
    "Tu es TontoumaBot, l'assistant administratif de l'hôpital. "
    "Réponds UNIQUEMENT à partir du contexte fourni ci-dessous."
)
CONSIGNE = (
    "Si l'information n'est pas dans le contexte, réponds exactement : INFORMATION_ABSENTE. "
    "Réponse claire et concise, en français."
)


def construire_prompt(contexte, question):
    return f"{ROLE_SYSTEME}\n\nCONTEXTE :\n{contexte}\n\n{CONSIGNE}\n\nQUESTION : {question}\nRÉPONSE :"


def generer_reponse(prompt, max_new_tokens=200):
    conversation = generator([{"role": "user", "content": prompt}], max_new_tokens=max_new_tokens, do_sample=False)
    return conversation[0]["generated_text"][-1]["content"].strip()


def repondre(question, top_k_final=5):
    resultat_retrieval = recuperer_chunks(question, top_k_final=top_k_final)
    contexte = "\n\n".join(resultat_retrieval["textes"])
    prompt = construire_prompt(contexte, question)

    t0 = time.perf_counter()
    reponse = generer_reponse(prompt)
    temps_generation_ms = (time.perf_counter() - t0) * 1000

    return {
        "question": question, "reponse": reponse, "contexte": contexte,
        "chunk_ids": resultat_retrieval["chunk_ids"],
        "latences": {**resultat_retrieval["latences"], "generation_ms": round(temps_generation_ms, 1)},
    }


resultat_final = repondre(question_test)
print(f"\nQuestion : {resultat_final['question']}")
print(f"Réponse  : {resultat_final['reponse']}")
print(f"Latences : {resultat_final['latences']}")

"""## 15. RAGAS — Retrieval / Generation / Performance

Évalue le pipeline complet sur un petit jeu de questions, scindé en trois familles de métriques comme dans le diagramme.
"""

jeu_test_rag = pd.DataFrame([
    {"id": "q1", "question": "Comment obtenir un extrait de naissance ?", "reference": "Se rendre au centre d'état civil avec les documents requis."},
    {"id": "q2", "question": "Où se trouve le service de radiologie ?", "reference": "Le service de radiologie se trouve au Bâtiment C."},
    {"id": "q3", "question": "Comment prendre rendez-vous avec un spécialiste ?", "reference": "Prendre rendez-vous au guichet ou par téléphone."},
    {"id": "q4", "question": "Combien coûte une consultation en cardiologie ?", "reference": "INFORMATION_ABSENTE"},
])

resultats_generation = []
for _, ligne in jeu_test_rag.iterrows():
    r = repondre(ligne["question"])
    resultats_generation.append({
        "id": ligne["id"], "question": ligne["question"], "reference": ligne["reference"],
        "reponse": r["reponse"], "contexte": r["contexte"], "chunk_ids": r["chunk_ids"],
        **r["latences"],
    })

df_generation = pd.DataFrame(resultats_generation)
display(df_generation[["id", "question", "reponse", "retrieval_total_ms", "generation_ms"]])

!pip install ragas datasets langchain-huggingface

!pip install ragas datasets langchain-huggingface
RAGAS_OK = False
try:
    from datasets import Dataset
    from ragas import evaluate
    from ragas.metrics import context_precision, context_recall, faithfulness, answer_relevancy
    from ragas.llms import LangchainLLMWrapper
    from ragas.embeddings import LangchainEmbeddingsWrapper
    from langchain_huggingface import HuggingFacePipeline, HuggingFaceEmbeddings

    ragas_llm = LangchainLLMWrapper(HuggingFacePipeline(pipeline=generator))
    ragas_embeddings = LangchainEmbeddingsWrapper(HuggingFaceEmbeddings(model_name=EMBEDDING_MODEL))

    lignes_ragas = [
        {"user_input": row["question"], "retrieved_contexts": [row["contexte"]],
         "response": row["reponse"], "reference": row["reference"]}
        for _, row in df_generation.iterrows()
    ]
    dataset_ragas = Dataset.from_list(lignes_ragas)

    resultats_ragas = evaluate(
        dataset_ragas, metrics=[context_precision, context_recall, faithfulness, answer_relevancy],
        llm=ragas_llm, embeddings=ragas_embeddings,
    )
    df_ragas = resultats_ragas.to_pandas()
    RAGAS_OK = True
    display(df_ragas)
except Exception as e:
    print(f" RAGAS non exécuté ({type(e).__name__}: {e}) -> pip install ragas datasets langchain-huggingface")
    df_ragas = pd.DataFrame()

import matplotlib.pyplot as plt

print("=== RETRIEVAL ===")
if RAGAS_OK:
    print(f"Context precision moyen : {df_ragas['context_precision'].mean():.3f}")
    print(f"Context recall moyen    : {df_ragas['context_recall'].mean():.3f}")
else:
    print("Non disponible sans RAGAS (voir cellule précédente).")

print(f"Latence retrieval moyenne : {df_generation['retrieval_total_ms'].mean():.0f} ms")

print("\n=== GENERATION ===")
if RAGAS_OK:
    print(f"Faithfulness moyen      : {df_ragas['faithfulness'].mean():.3f}")
    print(f"Answer relevancy moyen  : {df_ragas['answer_relevancy'].mean():.3f}")
else:
    print("Non disponible sans RAGAS.")

print(f"Latence génération moyenne : {df_generation['generation_ms'].mean():.0f} ms")

print("\n=== PERFORMANCE ===")
df_generation["latence_totale_ms"] = df_generation["retrieval_total_ms"] + df_generation["generation_ms"]
print(f"Latence totale moyenne : {df_generation['latence_totale_ms'].mean():.0f} ms")
print(f"Latence totale médiane : {df_generation['latence_totale_ms'].median():.0f} ms")
print(f"Latence totale P95     : {np.percentile(df_generation['latence_totale_ms'], 95):.0f} ms")

# Graphique récapitulatif
fig, axes = plt.subplots(1, 2, figsize=(12, 5))
df_generation.set_index("id")[["retrieval_total_ms", "generation_ms"]].plot(kind="bar", stacked=True, ax=axes[0])
axes[0].set_title("Décomposition de la latence par question")
axes[0].set_ylabel("ms")

if RAGAS_OK:
    df_ragas[["context_precision", "context_recall", "faithfulness", "answer_relevancy"]].mean().plot(kind="bar", ax=axes[1], color="#4C72B0")
    axes[1].set_title("Scores RAGAS moyens")
    axes[1].set_ylim(0, 1)

plt.tight_layout()
plt.show()

!pip show ragas
!pip show langchain

!pip install --upgrade ragas datasets langchain-huggingface
!pip show ragas
!pip show langchain